<a href="https://colab.research.google.com/github/andaleeb028/Andaleeb-Tarannum/blob/main/Assignment_1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Question 1**

In [1]:
!pip install numpy
import numpy as np
a= np.zeros(10,dtype='int32')
a[4]=1
print(a)


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
[0 0 0 0 1 0 0 0 0 0]


# **Question 2**

In [2]:
a=np.random.randint(10,49,size=(10))
print(a)

[37 35 24 35 47 17 25 15 43 36]


# **Question 3**

In [3]:
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# **Question 4**

In [4]:
a= np.array([1,2,0,0,4,0])
for i in range(6) :
 if a[i]!=0 : 
    print(i)

0
1
4


# **Question 4**

In [5]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.099725   0.78481462 0.16994193 0.44565341 0.98050141 0.86431617
  0.34313971 0.78243813 0.68239875 0.93075785]
 [0.60623917 0.5009267  0.89019723 0.16218122 0.90267595 0.42473591
  0.82874167 0.44999061 0.83304542 0.73859421]
 [0.9320736  0.19280984 0.875326   0.78722398 0.55463268 0.49612214
  0.53988916 0.05130033 0.66440505 0.10341972]
 [0.59264028 0.731806   0.20203123 0.46052452 0.36052758 0.06936284
  0.44356504 0.94013452 0.25544494 0.05738946]
 [0.10463789 0.86106012 0.32200599 0.16491048 0.51617549 0.61508171
  0.35413978 0.54086039 0.96539727 0.69922743]
 [0.44142267 0.27214556 0.79669767 0.9022538  0.19202824 0.43563344
  0.38408331 0.07524991 0.91218145 0.05370744]
 [0.68966778 0.77346107 0.21306342 0.92921287 0.83646771 0.13163051
  0.7015162  0.54812407 0.6688143  0.1251959 ]
 [0.93271238 0.76784865 0.77952991 0.0901524  0.73896341 0.92899611
  0.14484258 0.84864874 0.82825475 0.8805662 ]
 [0.94936724 0.44796313 0.55918273 0.8439606  0.97211781 0.69998

# **Question 5**

In [6]:
a= np.random.randint(0,100,size=(30))
print(a)
np.mean(a)


[32 34 60 48 52 34 58  6 51 79 48 10 43 17 29  8 41 15 30 83 65 14 67 96
 78 94 34 53 34 20]


44.43333333333333